### ISSUE TITLE
BANE error with multiple cores

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#33] opened 2016-11-30 06:19 UTC
For some reason I'm getting an error running BANE on galaxy:

29730:INFO This is BANE v1.4.6-(2016-09-01)
29730:INFO using grid_size (17, 17), box_size (102, 102)
29730:INFO on data shape (5214, 4661)
29730:INFO using 20 cores
Traceback (most recent call last):
  File "/group/mwasci/code/bin/BANE.py", line 5, in 
    pkg_resources.run_script('AegeanTools==v2.0b-46-g24246a4-master-',
'BANE')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 492, in
run_script
    """
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1350, in
run_script
    return open(self._fn(self.module_path, resource_name), 'rb')
  File
"/group/mwasci/code/lib/python2.6/site-packages/AegeanTools-v2.0b_46_g24246a4_master_-py2.6.egg/EGG-INFO/scripts/BANE",
line 66, in 
    mask=options.mask, compressed=options.compress)
  File
"/group/mwasci/code/lib/python2.6/site-packages/AegeanTools-v2.0b_46_g24246a4_master_-py2.6.egg/AegeanTools/BANE.py",
line 404, in filter_image
    bkg, rms = filter_mc_sharemem(im_name, step_size=step_size,
box_size=box_size, cores=cores, shape=shape)
  File
"/group/mwasci/code/lib/python2.6/site-packages/AegeanTools-v2.0b_46_g24246a4_master_-py2.6.egg/AegeanTools/BANE.py",
line 332, in filter_mc_sharemem
    pool.map(sf2, args)
  File
"/pawsey/cle52up04/apps/gcc/4.3.4/python/2.6.9/lib/python2.6/multiprocessing/pool.py",
line 148, in map
    return self.map_async(func, iterable, chunksize).get()
  File
"/pawsey/cle52up04/apps/gcc/4.3.4/python/2.6.9/lib/python2.6/multiprocessing/pool.py",
line 422, in get
    raise self._value
ValueError: Can only assign sequence of same size
^[[0;33mWARNING^[[0m: AstropyDeprecationWarning: Python 2.6 will no longer
be supported from Astropy v1.2.0 and above [astropy]

But it works fine if I use a single core:

29756:INFO This is BANE v1.4.6-(2016-09-01)
29756:INFO using grid_size (17, 17), box_size (102, 102)
29756:INFO on data shape (5214, 4661)
29756:INFO using 1 cores
29756:INFO done
29756:INFO Wrote ', mode 'w+b' at 0x1732270>
29756:INFO running second pass to get a better rms
29756:INFO using 1 cores
29756:INFO Wrote mosaic_20140610_080-088MHz_r-1.0_recomb_polyapplied_bkg.fits
29756:INFO Wrote mosaic_20140610_080-088MHz_r-1.0_recomb_polyapplied_rms.fits

I'm just doing $aprun BANE --noclobber --compress $file

with this BANE:

nhurleywalker@galaxy-1:~/queue> which BANE
/group/mwasci/code/bin/BANE

Version:
3982:INFO This is BANE v1.4.6-(2016-09-01)

Loaded modules:
Currently Loaded Modulefiles:
  1) slurm/14.11.8-pawsey-3                15) pmi/5.0.4-1.0000.10161.132.4.ari      29) traceback2/1.3.0                      43) distribute/0.6.49                     57) blist/1.3.6
  2) pawseytools/1.9                       16) dmapp/7.0.1-1.0502.11080.8.76.ari     30) unittest2/1.1.0                       44) matplotlib/1.5.0                      58) scipy/0.16.1
  3) rsync/3.1.1                           17) gni-headers/4.0-1.0502.10859.7.8.ari  31) numpy/1.10.1                          45) astropy/1.1                           59) lmfit/0.9.1
  4) modules/3.2.10.3                      18) xpmem/0.1-2.0502.64982.5.3.ari        32) cython/0.23.4                         46) memory_profiler/0.40                  60) healpy/1.9.1
  5) eswrap/1.1.0-1.020200.1231.0          19) job/1.5.5-0.1_2.0502.61936.2.32.ari   33) pkgconfig/1.1.0                       47) m4/1.4.17                             61) scikit-learn/0.17
  6) switch/1.0-1.0502.60522.1.61.ari      20) dvs/2.5_0.9.0-1.0502.2188.1.116.ari   34) cray-hdf5/1.8.13                      48) flex/2.6.0                            62) gsl/1.16
  7) craype-network-aries                  21) alps/5.2.4-2.0502.9774.31.11.ari      35) argparse/1.4.0                        49) bison/3.0.4                           63) boost/1.49.0
  8) gcc/4.8.2                             22) rca/1.0.0-2.0502.60530.1.62.ari       36) six/1.10.0                            50) sip/4.17                              64) cmake/2.8.12.2
  9) craype/2.1.2                          23) atp/1.7.3                             37) h5py/2.5.0                            51) pyephem/3.7.6.0                       65) cfitsio/3370
 10) craype-ivybridge                      24) PrgEnv-gnu/5.2.82                     38) emcee/2.1.0                           52) doxygen/1.8.9.1                       66) wcslib/5.11
 11) cray-mpich/7.0.0                      25) python/2.6.9                          39) python-dateutil/2.4.2                 53) java/jdk1.7.0_45                      67) readline/5.1
 12) cray-libsci/13.0.0                    26) lapack/3.5.0                          40) pytz/2015.7                           54) fftw/3.3.4.3
 13) udreg/2.3.2-1.0502.10518.2.17.ari     27) setuptools/18.4                       41) mock/1.3.0                            55) pigz/2.3.3
 14) ugni/6.0-1.0502.10863.8.29.ari        28) linecache2/1.0.0                      42) nose/1.3.7                            56) psycopg2/2.6.1

**Comment by gheald** [comment] 2018-05-03 02:25
Is there a workaround for this (other than using --cores=1)? I am encountering the same error. This is on a linux machine (not a Pawsey system) running Ubuntu 16 and having just installed the current version of Aegean via pip.

**Comment by PaulHancock** [comment] 2018-05-03 07:44
George - due to slackness on my part the version of aegean you get from pip is not the current version.
Can you uninstall the version you have (`pip uninstall aegeantools`) and install the github version?

You can still use pip to do this: `pip install git+git://github.com/PaulHancock/Aegean.git`

If the problem persists then i'm very interested to try and recreate it so that I can debug it.

**Comment by gheald** [comment] 2018-05-03 08:39
Thanks Paul - I think that I was unclear! I installed Aegean like so:
pip install git+https://github.com/PaulHancock/Aegean.git
(install option #3 I believe from the docs) which is presumably the same as what you suggested? I didn't use pip to install the 'stable' Aegean out of pypi.

**Comment by PaulHancock** [comment] 2018-05-04 03:40
Yes that install method will give you the most recent version - so your problem is with the current version of aegean.

Are you able to create some minimal working example that will reproduce the error that I can use for testing? Alternatively we can meet up and I can test a few things directly on your computer. (lets chat via email about this).

**Comment by PaulHancock** [comment] 2018-05-11 01:50
This bug has been fixed in the latest version.

**Closed by PaulHancock** 2018-05-11 01:50 UTC
Labels: BANE, bug
