### ISSUE TITLE
AttributeError when running aegean.py and select.poll() in BANE.py

### ISSUE THREAD

**Issue by Sharkkie** [PaulHancock/Aegean#21] opened 2015-10-15 07:26 UTC
Hi, I've been trying aegean.py according to the wiki.
However it always return error as follows:

>python aegean.py Test/Images/1904-66_SIN.fits
aegean:INFO This is Aegean v1.9.6-127-g088562b-(2015-10-02)
aegean:INFO Found 4 cores
aegean:WARNING Your O/S doesn't support select.poll(): Reverting to cores=1
aegean:INFO Using 1 cores
aegean:INFO Finding sources.
aegean:INFO Calculating curvature csigma
aegean:INFO Calculating background and rms data
aegean:INFO beam = 864.00'' x 864.00'' at  0.00deg
aegean:INFO seedclip=5
aegean:INFO floodclip=4
#Aegean version v1.9.6-127-g088562b-(2015-10-02)
#on dataset: Test/Images/1904-66_SIN.fits
#isl,src   bkg       rms         RA           DEC         RA         err         DEC        err         Peak      err     S_int     err        a    err    b    err     pa   err   flags
#Jy/beam   Jy/beam                               deg        deg         deg        deg       Jy/beam   Jy/beam    Jy       Jy         ''    ''    ''    ''    deg   deg   WNCPES
#===========================================================================================================================================================================================
Traceback (most recent call last):
  File "aegean.py", line 2270, in <module>
    mask=options.region, lat=lat, imgpsf=options.imgpsf)
  File "aegean.py", line 1501, in find_sources_in_image
    res = fit_island(island_data)
  File "aegean.py", line 1373, in fit_island
    result, model = do_lmfit(idata, params, B=B)
  File "/Users/yw_astro/Software/Astro_Soft/Aegean-master/AegeanTools/fitting.py", line 383, in do_lmfit
    result = lmfit.minimize(residual, params, kws={'x':mask[0],'y':mask[1],'B':B,'errs':errs}, Dfun = jacobian)
  File "/Library/Python/2.7/site-packages/lmfit/minimizer.py", line 773, in minimize
    return fitter.minimize(method=method)
  File "/Library/Python/2.7/site-packages/lmfit/minimizer.py", line 705, in minimize
    return function(**kwargs)
  File "/Library/Python/2.7/site-packages/lmfit/minimizer.py", line 546, in leastsq
    lsout = scipy_leastsq(self.__residual, vars, **lskws)
  File "/Library/Python/2.7/site-packages/scipy/optimize/minpack.py", line 371, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/Library/Python/2.7/site-packages/scipy/optimize/minpack.py", line 20, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/Library/Python/2.7/site-packages/lmfit/minimizer.py", line 257, in __residual
    out = self.userfcn(params, *self.userargs, **self.userkws)
  File "/Users/yw_astro/Software/Astro_Soft/Aegean-master/AegeanTools/fitting.py", line 376, in residual
    model = f(*mask)  # The actual model
  File "/Users/yw_astro/Software/Astro_Soft/Aegean-master/AegeanTools/fitting.py", line 343, in rfunc
    for i in range(params.components):
AttributeError: 'Parameters' object has no attribute 'components'

I'm not sure whether it's a problem of lmfit, but I've already tried to reinstall it both from the source code or by pip for many times...
Another problem is that the select.poll() in BANE.py seems to be failed on my mac( osx 10.11), is this a general problem for python on Mac or sth. wrong with mine?

Thank you.

**Comment by PaulHancock** [comment] 2015-10-15 08:48
Sharkkie,

The AttributeError that you encounter is likely due to your version of lmfit (see issue #19). The issue is resolved in the dev branch of Aegean v1.9.6-107-geb1c4e6-(2015-10-06), and will be pushed to the master branch soon.

The problem with select.poll() is likely an OSX problem, however I have tried to catch the error and work around it when it occurs. If BANE is crashing on you then I have some more work to do. If you could include a trace of the BANE error then I can track down the problem and get a fix on the way.

Paul.

**Comment by Sharkkie** [comment] 2015-10-15 09:31
Hi Paul,
Thank you for the reply. I'm trying lmfit v0.8.3 and it works fine!
The select.poll() problem is as follows (I've also tried  similar functions ):

>
In [12]: select.kqueue
Out[12]: select.kqueue
In [13]: poll.poll
Out[13]: <function poll.poll>
In [14]: select.poll
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-3cab225fcfbd> in <module>()
----> 1 select.poll
AttributeError: 'module' object has no attribute 'poll'

I've referred to this link when I tried to solve this problem: http://stackoverflow.com/questions/19740471/cannot-use-python-select-poll-in-mac-os

Yuwei

**Comment by PaulHancock** [comment] 2015-10-15 10:05
Yuwei,

Ok so now that I see that post again I recall how I got around this problem on my mac. 

It seems that the default version of python that comes with some (most?) macs, doesn't support the select.poll() call, however this isn't a limitation of the hardware, or even the OS, it's just the hacked-up version of python that is included.

On my own system I used macports to install a second version of python (2.7) and use this as my default. I then installed all the modules that I needed (scipy etc..). When I run this version of python I don't get any select.poll() issues.

Maybe a similar approach will work for you.

Paul.

**Comment by jessica-norris** [comment] 2015-10-15 10:10
Hi Paul,

Thanks for this information - I see that I will have the poll() problem, but I’ve used macports before (I’m not sure why I moved away from it now, but it can’t be too hard to get or compile my own python version that has poll()).

I will just make myself a virtual environment with all the bits I need.

Cheers
Jess

**Comment by Sharkkie** [comment] 2015-10-16 01:34
Thank you, Paul! :D

**Closed** 2016-02-14 16:35 UTC
Labels: bug
