### ISSUE TITLE
Island fluxes do not match integrated fluxes

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#13] opened 2015-03-30 04:32 UTC
I run Aegean with the --island option and cross-match the resulting _isle and _comp tables with an exact match on the island column. When I plot the integrated flux as derived from the component fit against the integrated flux (divided by eta) as derived from the island floodfill, the results are out by a factor of three. Seedclip is 8 and floodclip is 5, so at the faint end it might be somewhat understandable (although eta should fix that) but it doesn't make a lot of sense at the high end. Linear and log plots attached.
![island_v_int_linear](https://cloud.githubusercontent.com/assets/8326966/6890192/d41cd49a-d6d8-11e4-813b-78b644449a88.png)
![island_v_int_log](https://cloud.githubusercontent.com/assets/8326966/6890193/d41ead92-d6d8-11e4-895a-4a3ff930c79b.png)

**Comment by PaulHancock** [comment] 2015-10-02 03:36
This has been fixed in the master branch as of 2/10/15.

**Closed by PaulHancock** 2015-10-02 03:36 UTC

**Comment by rmalexan** [comment] 2016-01-21 19:54
I cloned the repo of Aegean today (just to check) and ran a similar test to find what appears to be the same mismatch between the component and island integrated flux (again matching on the island column) -- see attached.  Is there a flag to turn on or something else I should be aware of?  
![image](https://cloud.githubusercontent.com/assets/4950184/12492564/d13f55f8-c04e-11e5-9c73-85c74e4065ed.png)

**Comment by PaulHancock** [comment] 2016-01-22 08:05
rmelaxan,

Despite my previous posts, it appears that the solved bug has been reintroduced to the master branch of Aegean. The good news is that the current development branch has fixed this issue. 

It seems that the issue is related to the integrated island flux that is calculated by Aegean. On the 1904-66_SIN.fits test image, the current master branch gives an island flux that is about 15% of what I would expect. The current dev branch gives the expected flux, and the island int/eta calculation gives a 1:1 match to the component integrated flux..

I plan to push the changes in the dev branch onto the master branch next week. You can either use the dev branch now or wait for me to push the changes to the master branch.

Paul.
