### ISSUE TITLE
BANE crashes if BSCALE is used due to memmap=True

### ISSUE THREAD

**Issue by Sunmish** [PaulHancock/Aegean#122] opened 2020-06-18 05:28 UTC
BANE is currently crashing if BSCALE is used (and I believe if it is not 1) because BSCALE is not compatible with `memmap=True`. 

A workaround is to use `do_not_scale_image_data=True` in `fits.open` within the `sigma_filter` function, and operations are then performed on unscaled data, which should (?) be fine as the BSCALE keyword should be propagated into the rms and bkg image headers later on when the images are written to disk anyway.  

I'm unsure how this affects aegean (read: I haven't look into how it affects aegean).

**Comment by PaulHancock** [comment] 2020-06-19 06:01
Thanks for this report and for your suggestion.

`do_not_scale_image_data=True` does indeed avoid the crash, however since the `sigma_filter` function is exposed part of the API i'll do the BSCALE correction manually so that we always get the right answer. I'll scale back again when we save to a file.

**Comment by PaulHancock** [comment] 2020-06-19 06:06
commits fe68c3c, 4ecc3c9, and b7113adc6, are relevant to this ticket but I mis-tagged them :(

**Comment by PaulHancock** [comment] 2020-06-19 06:10
I can confirm that Aegean is immune to this problem because it doesn't use `memmap` to load the fits files (although it should).

**Comment by PaulHancock** [comment] 2020-06-20 07:02
This issue has been fixed as of PR #123

**Closed by PaulHancock** 2020-06-20 07:02 UTC
Labels: BANE
