### ISSUE TITLE
Aegean help!

### ISSUE THREAD

**Issue by ashy2212** [PaulHancock/Aegean#178] opened 2022-07-11 12:38 UTC
Hi Paul, 

I am new to radio astronomy and python programming however I have lots of radio images I need to extract source parameters. I have installed Aegean on my machine and I am attempting the steps outlined in the Quick Start Guide. 

I am getting an error in my terminal window that I do not understand(attached)

I am using python 3.8.8, or MacOS Big Sur is this the problem?

Many thanks,

Ash

<img width="1304" alt="Screenshot 2022-07-11 at 13 37 22" src="https://user-images.githubusercontent.com/108931007/178265812-c794a01a-ebb5-48b8-b034-999f02b8c9c2.png">

**Comment by PaulHancock** [comment] 2022-07-12 01:32
Hi Ash,

The issue that you describe here is the same as #137 -> Multiprocessing on mac with python 3.8 or later is currently broken for Aegean. Currently the only suggestion that I have is to either use a different computer (a linux based machine) or to run AegeanTools from within a container (see the discussion in #137 for a note about the container solution).

This issue is on my road-map for development however I don't yet have a timeline for completion.

Paul.

**Comment by PaulHancock** [comment] 2022-08-11 02:27
Closing as a duplicate of #137

**Closed by PaulHancock** 2022-08-11 02:27 UTC
Labels: duplicate, Aegean, osx
